### PR TITLE
Appveyor: build x86 & x64

### PR DESCRIPTION
**Pull request by Jan-E**
Proof of the pudding:
https://ci.appveyor.com/project/Jan-E/pthreads/build/master.1

### CODE REVIEW

**Comment by Jan-E** [comment]
@krakjoe: https://ci.appveyor.com/project/krakjoe/pthreads/build/master.173
Please merge

**Comment by dktapps** [comment]
You can set arch using the `platform` variable, which can help create a less messy matrix. 
```
platform:
 - x86
  -x64
``
which is then accessible via `PLATFORM` in the cmd itself. See https://github.com/php/php-src/blob/master/.appveyor.yml#L49

**Comment by Jan-E** [comment]
'messy' is a matter of taste.
```
  matrix:
    - ARCH: x86
      PHP_VER: 7.2
      VC_VER: vc15
    - ARCH: x64
      PHP_VER: 7.2
      VC_VER: vc15
```
tells me instantly that I am testing the x86 & x64 builds of the extension for PHP 7.2

**Comment by krakjoe** [comment]
Thanks @Jan-E ... sorry about delay, business happened ...

**Pull request merged**
