### PR TITLE
Copy stdin, stdout and stderr at thread creation

### PR DESCRIPTION
**Pull request by SirSnyder**
This PR copies the streams stdin, stdout and stderr(if available) to new threads at creation and independently of start options. See #806 and #583

### CODE REVIEW

**Comment by dktapps** [comment]
Since they are resources, I was under the impression they would be unsafe to copy from the origin thread? I thought it would be better to just recreate them on the child.

**Comment by krakjoe** [comment]
Correct, this would be unsafe ...

There might be a way to do it by dup'ing the handles and using the streams API to reimport them in the new thread ... I'd go with that, if anything ...

**Comment by CharlotteDunois** [comment]
@SirSnyder Is there any update on this?

**Comment by SirSnyder** [comment]
Not yet, maybe in 3 or 4 weeks.

**Comment by SirSnyder** [comment]
@krakjoe can you have a look at the last commit in this PR, is the implementation ok?

**Comment by dktapps** [comment]
@SirSnyder I don't know any crashing condition, but this is inherently unsafe anyway since these are resources.

**Comment by SirSnyder** [comment]
@dktapps from php vm perspective this should be ok. The resources are created per thread context and not shared between them. So there is no resource/memory dependency to another thread. What can happen are race conditions by reading/writing to the streams. Developers have to sync them by hand. I think I'll wait for that until `FileStream`s are implemented.

**Comment by tpunt** [comment]
On the one hand, this seems fine to me. Multiple threads writing to the same output will obviously incur race conditions without any kind of synchronisation, so anyone using this should synchronise the access for a predictable output (and I don't see any ways for this to crash from PHP's VM from such race conditions). But on the other hand, there's probably a nicer way to expose writing in an atomic way (e.g. to write strings in full, implicitly serialising them one after another without having output interleaved). I'm not against this PR, though.

**Comment by dktapps** [comment]
fwiw, the reason I originally wanted this was because I had some library code that did checks on `STDOUT` to check for ANSI colour code support (it disables colours on pipes). I didn't really put any consideration into how they would be used for actual stdio.

**Comment by SirSnyder** [comment]
@tpunt I have had the idea to replace the STD* constants by FileStream objects from https://github.com/krakjoe/pthreads/tree/streams. But that was just a crazy idea. I would say this stuff can get merged.

**Comment by SirSnyder** [comment]
Thanks to all involved!

**Comment by dktapps** [comment]
This has caused some problems for PM on Windows. Threads hang on start until the user presses the enter key on the console. I'm still trying to gauge the scope of the issue and reproducing test case, but this is not bug free.

**Comment by dktapps** [comment]
@sirsnyder it would be appreciated if you could revert the merge, it makes things difficult for PRs since I have to omit this commit to be able to test anything.

**Comment by sirsnyder** [comment]
@dktapps reverted

**Pull request merged**
