### PR TITLE
Fix Appveyor run-tests

### PR DESCRIPTION
**Pull request by Jan-E**
Try a minimal php.ini

### CODE REVIEW

**Comment by Jan-E** [comment]
@krakjoe First shot was a direct hit:
https://ci.appveyor.com/project/krakjoe/pthreads/build/master.167#L645
Please merge

**Comment by Jan-E** [comment]
Small cleanup: I merged the 2 commits I had at the first shot.

**Comment by dktapps** [comment]
I think you can also remove `--with-config-file-scan-dir=C:\projects\pthreads\bin\modules.d` from `configure`, it doesn't appear to be necessary with these changes.

**Comment by Jan-E** [comment]
This must be a bad dream for @krakjoe : the Windows build env is now better than the *nix one.

**Pull request merged**
