### PR TITLE
#816 - keep refcount as set by unserialize

### PR DESCRIPTION
**Pull request by SirSnyder**

### CODE REVIEW

**Comment by SirSnyder** [comment]
A test for this case is still missing

**Comment by SirSnyder** [comment]
I have added a test.

**Comment by tpunt** [comment]
Looks good to me. I'm not quite sure why the refcount was reset in the first place. The setting of the `pzval` to null is a little redundant, since it will be set to null in the calling function (it will also be set to null by the calling function of the calling function... But perhaps that can be cleaned up later).

**Comment by SirSnyder** [comment]
@dktapps nice to see
@tpunt thanks for the hint, I've removed the nulling

**Pull request merged**
